name: Deploy PR previews

on:
  workflow_dispatch:
  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

env:
  INPUT_PATH: "."
  PREVIEW_FOLDER: "/pr-preview" # subfolder
  pr: ${{ github.event.number }}
  OSSI_SITE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  action: auto
  preview-branch: main
  actionref: ${{ github.action_ref }}
  actionrepo: ${{ github.action_repository }}
  deployrepo: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Store environment variables
        run: |
          org=$(echo "${{env.deployrepo}}" | cut -d "/" -f 1)
          thirdleveldomain=$(echo "${{env.deployrepo}}" | cut -d "/" -f 2)

          if [ "${org}.github.io" == "$thirdleveldomain" ]; then
            pagesurl="${org}.github.io"
          else
            pagesurl=$(echo "${{env.deployrepo}}" | sed 's/\//.github.io\//')
          fi
          echo "pagesurl=$pagesurl" >> $GITHUB_ENV
          echo "PREVIEW_PATH=${{env.PREVIEW_FOLDER}}/pr-${{env.pr}}" >> $GITHUB_ENV
          echo "emptydir=$(mktemp -d)" >> $GITHUB_ENV
          echo "datetime=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine auto action
        run: bash .github/actions/determine-auto-action.sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.INPUT_PATH }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.INPUT_PATH }}

      - name: Build with Astro
        run: |
          npx --no-install astro build \
            --site "https://${{ env.pagesurl }}" \
            --base "${{ env.PREVIEW_PATH }}" \
            --outDir "$GITHUB_WORKSPACE/${{env.PREVIEW_PATH}}/dist" \
            --cacheDir "$GITHUB_WORKSPACE/${{env.PREVIEW_PATH}}/node_modules/.astro"
        working-directory: ${{ env.INPUT_PATH}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: $GITHUB_WORKSPACE/${{env.PREVIEW_PATH}}/dist
          target-folder: ${{env.PREVIEW_PATH}}
          force: false

      - name: Expose deployment URL
        id: url
        run: echo "url=https://${{ env.pagesurl }}/${{ env.PREVIEW_PATH }}/"  >> $GITHUB_OUTPUT
        shell: bash

      - name: Leave a comment after deployment
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        with:
          header: pr-preview
          message: "
            :rocket: Deployed preview to
            https://${{ env.pagesurl }}/${{ env.PREVIEW_PATH }}/

            on branch [`${{ env.preview-branch }}`](\
            ${{ github.server_url }}/${{ env.deployrepo }}\
            /tree/${{ env.preview-branch }})
            at ${{ env.datetime }}
            "
